orangehrm_app:
  image: 285645945015.dkr.ecr.us-east-1.amazonaws.com/ohrm-enterprise:5.3v2
  restart: until_stopped
  container_name: orangehrm_app
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
    - VIRTUAL_HOST=orangehrm
    - OHRM_DB_NAME=orangehrm
    - OHRM_DB_HOST=dbserver
    - OHRM_DB_USER=root
    - OHRM_DB_PASS=root
    - OHRM_ADMIN_PASS=admin
    - OHRM_SYSADMIN_PASS=admin
  links:
    - orangehrm_db:dbserver

orangehrm_db:
  container_name: orangehrm_db
  image: mysql:5.5
  restart: always
  environment:
    - MYSQL_ROOT_PASSWORD=root


orangehrm_proxy:
  container_name: orangehrm_proxy
  image: nginx:alpine
  restart: always
  ports:
    - 7070:80